### ISSUE TITLE
Load ircb data from file

### ISSUE THREAD

**Issue by rtnpro** [waartaa/ircb#25]
### Problem statement

Currently we add data: user, network data in ircb using `ircb` cli. This can prove tedious sometimes. It'd be great if we could load this data from a **YAML** file. This'd allow `ircb` service providers to maintain this file in a git repository, and adopt a simple git workflow to grant users access.
### Implementation details

Possible file content could have the following schema:

```

---
username1:
  email: username1@some-email.com
  networks:
    network1:
      nick: some-nick
      host: ...
      port: ...
      realname: ...
      username: ...
      password: ...
      usermode: ...
    network2:
      ...
username2:
  ...
```
